/* Generated By:JavaCC: Do not edit this line. NameParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NameParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int AND = 6;
  /** RegularExpression Id. */
  int HON = 7;
  /** RegularExpression Id. */
  int MR = 8;
  /** RegularExpression Id. */
  int MRS = 9;
  /** RegularExpression Id. */
  int MISS = 10;
  /** RegularExpression Id. */
  int MS = 11;
  /** RegularExpression Id. */
  int MADAM = 12;
  /** RegularExpression Id. */
  int SIR = 13;
  /** RegularExpression Id. */
  int ATTY = 14;
  /** RegularExpression Id. */
  int PROF = 15;
  /** RegularExpression Id. */
  int DOCTOR = 16;
  /** RegularExpression Id. */
  int BAR = 17;
  /** RegularExpression Id. */
  int BEN = 18;
  /** RegularExpression Id. */
  int BIN = 19;
  /** RegularExpression Id. */
  int BINTI = 20;
  /** RegularExpression Id. */
  int BINTE = 21;
  /** RegularExpression Id. */
  int DA = 22;
  /** RegularExpression Id. */
  int DE = 23;
  /** RegularExpression Id. */
  int DAL = 24;
  /** RegularExpression Id. */
  int DELA = 25;
  /** RegularExpression Id. */
  int DE_LA = 26;
  /** RegularExpression Id. */
  int DER = 27;
  /** RegularExpression Id. */
  int DI = 28;
  /** RegularExpression Id. */
  int ESTATE_OF = 29;
  /** RegularExpression Id. */
  int IBN = 30;
  /** RegularExpression Id. */
  int LA = 31;
  /** RegularExpression Id. */
  int LE = 32;
  /** RegularExpression Id. */
  int L_APOST = 33;
  /** RegularExpression Id. */
  int MAC = 34;
  /** RegularExpression Id. */
  int MC = 35;
  /** RegularExpression Id. */
  int OH = 36;
  /** RegularExpression Id. */
  int SAN = 37;
  /** RegularExpression Id. */
  int ST = 38;
  /** RegularExpression Id. */
  int STE = 39;
  /** RegularExpression Id. */
  int VAN_DER = 40;
  /** RegularExpression Id. */
  int VAN = 41;
  /** RegularExpression Id. */
  int VAN_DEN = 42;
  /** RegularExpression Id. */
  int VEL = 43;
  /** RegularExpression Id. */
  int VON = 44;
  /** RegularExpression Id. */
  int INC = 45;
  /** RegularExpression Id. */
  int LTD = 46;
  /** RegularExpression Id. */
  int CO = 47;
  /** RegularExpression Id. */
  int TM = 48;
  /** RegularExpression Id. */
  int SECOND = 49;
  /** RegularExpression Id. */
  int THIRD = 50;
  /** RegularExpression Id. */
  int FOURTH = 51;
  /** RegularExpression Id. */
  int LLB = 52;
  /** RegularExpression Id. */
  int ESQ = 53;
  /** RegularExpression Id. */
  int JD = 54;
  /** RegularExpression Id. */
  int PHD = 55;
  /** RegularExpression Id. */
  int BBA = 56;
  /** RegularExpression Id. */
  int MBA = 57;
  /** RegularExpression Id. */
  int BSC = 58;
  /** RegularExpression Id. */
  int MD = 59;
  /** RegularExpression Id. */
  int DDS = 60;
  /** RegularExpression Id. */
  int DMD = 61;
  /** RegularExpression Id. */
  int CP = 62;
  /** RegularExpression Id. */
  int SENIOR = 63;
  /** RegularExpression Id. */
  int JUNIOR = 64;
  /** RegularExpression Id. */
  int ROMAN_NUMERALS = 65;
  /** RegularExpression Id. */
  int QUOTED_NICK_NAME = 66;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_NICK_NAME = 67;
  /** RegularExpression Id. */
  int PAREN_NICK_NAME = 68;
  /** RegularExpression Id. */
  int NAME_WITH_NUMBERS = 69;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\",\"",
    "<AND>",
    "<HON>",
    "<MR>",
    "<MRS>",
    "<MISS>",
    "<MS>",
    "<MADAM>",
    "\"sir\"",
    "<ATTY>",
    "<PROF>",
    "<DOCTOR>",
    "\"bar\"",
    "\"ben\"",
    "\"bin\"",
    "\"binti\"",
    "\"binte\"",
    "\"da\"",
    "\"de\"",
    "\"dal\"",
    "\"dela\"",
    "\"de la\"",
    "\"der\"",
    "\"di\"",
    "\"estate of\"",
    "\"ibn\"",
    "\"la\"",
    "\"le\"",
    "<L_APOST>",
    "\"mac\"",
    "\"mc\"",
    "\"o\\\'\"",
    "\"san\"",
    "<ST>",
    "\"ste\"",
    "\"van der\"",
    "\"van\"",
    "\"van den\"",
    "\"vel\"",
    "\"von\"",
    "<INC>",
    "<LTD>",
    "<CO>",
    "\"tm\"",
    "<SECOND>",
    "<THIRD>",
    "<FOURTH>",
    "<LLB>",
    "<ESQ>",
    "<JD>",
    "<PHD>",
    "<BBA>",
    "<MBA>",
    "<BSC>",
    "<MD>",
    "\"dds\"",
    "\"dmd\"",
    "<CP>",
    "<SENIOR>",
    "<JUNIOR>",
    "<ROMAN_NUMERALS>",
    "<QUOTED_NICK_NAME>",
    "<SINGLE_QUOTED_NICK_NAME>",
    "<PAREN_NICK_NAME>",
    "<NAME_WITH_NUMBERS>",
  };

}
