package parser;

import com.google.common.base.Preconditions;
import parser.jj.NameParserConstants;

// TODO : extend this class so there is salutationToken, titleToken, relationToken
public class Token {

    int kind;
    String value;    // e.g. "Mr."    the value the user originally input.
    String tokenText;     // e.g. <MR>     the token image string.   generated by javacc.
    String normalizedText; // e.g. Mister      a user/db friendly standardized tring for value.
    NameTokenType type;


    Token(String value, int kind, NameTokenType type) {
        Preconditions.checkArgument(value != null);
        this.value = value;
        this.kind = kind;
        this.tokenText = NameParserConstants.tokenImage[kind];
        this.normalizedText = value;  // by default.
        this.type = type;

    }

    @Override
    public String toString() {
        return normalizedText;
    }

}